### PR TITLE
fix: stringify json before request, change key names in metrics

### PR DESCRIPTION
**Pull request by abhstabs**
Hi @khemrajrathore / @ojaswa1942, 

Changes to Stringify the Json before uploading to cloud. Also changed the key names as request by Vineet. Please have a look. 

Thank you.

cc: @pandurangpatil

### CODE REVIEW

**Comment by ojaswa1942** [comment]
Since it looks like we've added an external dependency, and we're still using the `ScalaDefautModule` - did we simply try `toString` to stringify?

**Comment by abhstabs** [comment]
`toString` only converts the Json object to a string. Doesn't actually _stringify_ the data that we were looking for. @khemrajrathore and I tried that yesterday.

**Review by khemrajrathore — APPROVED** [review]
LGTM

**Review by ojaswa1942 — APPROVED** [review]
:shipit:

**Pull request merged**
