### PR TITLE
Optmizied privado.json export

### PR DESCRIPTION
**Pull request by karan-batavia**
Added asynchronous calls for various data elements processing to get the time down for exporting the `privado.json` file.

### CODE REVIEW

**Review by abhstabs — APPROVED** [review]
LGTM!

**Comment by khemrajrathore** [comment]
🚫 Don't merge this to DEV

**Comment by khemrajrathore** [comment]
@pandurangpatil Review and add your comments

**Comment by pandurangpatil** [comment]
@karan-batavia we need to run the scan multiple times for at least 6 repos including this repo https://github.com/opencrx/opencrx in your test. Verify we are getting consistent results with each scan.

For verification, use a comparison script to compare the privado.json from one result with another result.

**Review by pandurangpatil — CHANGES_REQUESTED** [review]
@karan-batavia we need to run the scan multiple times for at least 6 repos including this repo https://github.com/opencrx/opencrx in your test. Verify we are getting consistent results with each scan.

For verification, use a comparison script to compare the privado.json from one result with another result.

**Review by pandurangpatil — APPROVED** [review]

**Pull request merged**
