### PR TITLE
Summary Report and External PR Support

### PR DESCRIPTION
**Pull request by ankit-privado**

### CODE REVIEW

**Review by abhstabs — APPROVED** [review]

**Comment by abhstabs** [comment]
LGTM!

**Review by abhstabs — APPROVED** [review]
LGTM!

**Comment by ojaswa1942** [comment]
Link to a successful run, please? @ankit-privado

**Comment by ankit-privado** [comment]
@ojaswa1942 Can we wait for some more days because we still not finalized the final output format. we are still working on adding more details in our comparison report. Once its done, i will let you know and will share a successful run without you.

**Comment by ojaswa1942** [comment]
@ankit-privado just looking for a successful workflow run with the changes made before merging this.

**Comment by pandurangpatil** [comment]
This change is no more required with the use of standalone comparison script integration. Hence closing this one.

**Pull request closed without merging**
