### PR TITLE
Fix: External script processing to work with scala 3

### PR DESCRIPTION
**Pull request by karan-batavia**
Using dotty `ScriptEngine` instead of scala reflection to run the external script. 
@khemrajrathore , please review.

### CODE REVIEW

**Comment by khemrajrathore** [comment]
- [ ] Add test case which verifies the behaviour of reading external script, so in future we can catch this effectively

Question - If script execution fails does scan continue or fails?

**Comment by karan-batavia** [comment]
> Question - If script execution fails does scan continue or fails?

@khemrajrathore, the regular scan will continue.

**Comment by karan-batavia** [comment]
> * [x]  Add test case which verifies the behaviour of reading external script, so in future we can catch this effectively
This is done, please review @khemrajrathore.

**Review by khemrajrathore — DISMISSED** [review]
LGTM

**Review by khemrajrathore — APPROVED** [review]
LGTM

**Pull request merged**
