### PR TITLE
Go: sync with dev

### PR DESCRIPTION
**Pull request by hiteshbedre**

### CODE REVIEW

**Comment by karan-batavia** [comment]
@hiteshbedre you'll have to incorporate similar changes for `DataflowCache` and `AuditCache` as instance variables for `Go` as well. 
cc: @pandurangpatil

**Comment by khemrajrathore** [comment]
Rightly pointed out @karan-batavia, @hiteshbedre PR for reference - https://github.com/Privado-Inc/privado-core/pull/745

**Comment by karan-batavia** [comment]
@hiteshbedre , I've done those changes myself. This should run the unit-tests successfully. 
cc: @khemrajrathore @pandurangpatil

**Review by pandurangpatil — APPROVED** [review]
looks good

**Pull request merged**
